version: '3.8'
services:
  ewm-gateway:
    build: ewm-gateway
    image: kazannik-ewm-gateway
    container_name: ewm-gateway
    ports:
      - "8080:8080"
      - "9090:9090"
    depends_on:
      - ewm-main-service
      - ewm-stats-service
      - ewm-feature-service
    environment:
      - MAIN_SERVER_URL=http://ewm-main-service:8080
      - STATS_SERVER_URL=http://ewm-stats-service:8080
      - FEATURE_SERVER_URL=http://ewm-feature-service:8080

  ewm-main-service:
    build: ewm-main-service
    image: kazannik-ewm-main
    container_name: ewm-main
    ports:
      - "6540:8080"
    depends_on:
      - ewm-main-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-main-db:5432/main-db

  ewm-main-db:
    image: postgres:14-alpine
    container_name: ewm-postgres
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=main-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-stats-service:
    build: ewm-stats-service
    image: kazannik-ewm-stats
    container_name: ewm-stats
    depends_on:
      - ewm-stats-db
    ports:
      - "6542:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-stats-db:5432/stats-db

  ewm-stats-db:
    image: postgres:14-alpine
    container_name: stats-postgres
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-feature-service:
    build: ewm-feature-service
    image: kazannik-ewm-feature
    container_name: ewm-feature
    depends_on:
      - ewm-main-service
      - ewm-feature-db
    ports:
      - "6544:8080"
    environment:
      - MAIN_SERVER_URL=http://ewm-main-service:8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-feature-db:5432/feature-db

  ewm-feature-db:
    image: postgres:14-alpine
    container_name: feature-postgres
    ports:
      - "6545:5432"
    environment:
      - POSTGRES_DB=feature-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root